#!/usr/bin/env python3
"""VERIFIER step 3.1: recompute a manifest's published constants from the PUBLIC checkpoint,
on a CPU, without the serving engine, and compare every tensor digest.

    CUDA_VISIBLE_DEVICES= python verify_constants.py --model Qwen/Qwen2.5-1.5B-Instruct \\
        --manifest lockstep.manifest.json [--tp 1]

Contract v2.4 at R1 online, smoothing level 0, tensor parallel 1 (the rules of
docs/contract/NON_ATTENTION_STACK_v2.5.md sections 2, 4, 6.2, 6.3, 6.5 and 8), in the order
the fold applies them, with the same binary64 products and the same bf16 roundings:

  norms        G = rn_even(g * 2^17) int32 from the checkpoint's bf16 gain; the final norm's
               gain is folded into the head (G = 2^17 there);  s = fl32(sqrt(N) / 2^17)
  qkv_proj     rows [q | k | v] of the checkpoint's q/k/v; the v rows (and the v bias) take R2
               (block-diagonal Sylvester on the head dimension, fp64); every row takes the
               online R1 block rotation on its columns (256-block Sylvester / 16, fp64);
               bf16; per-output-channel int8 (section 2);  mode 1
  o_proj       W Bo (R2 in head space, fp64); bf16; int8;  mode 0
  gate_up_proj rows [gate | up]; the online R1 on the columns; bf16; rows padded to 256; int8; mode 1
  down_proj    columns padded to 256 then R4 (256-block Sylvester / 16, fp64); bf16; int8; mode 1
  embed        the checkpoint's bf16 table (unrotated under R1 online)
  lm_head      (W * g_final) in fp64, bf16, then the a15w15 planes of section 8
  rope         vLLM's cos/sin cache (binary32, held in bf16) on the Q14 grid (section 5): reproducible
               except the bf16 rounding-boundary entries where the device's cos / sin differ in the
               last bit (Qwen2.5-7B: 1,263 of 4,194,304 entries), so the table is verified by hash

Reports per kind: recomputed, matching, differing; exits 0 only when every tensor of the
manifest that this tool covers matches.  `keq.pt` (the key offset) is a calibration
constant regenerated by `k_equalize.py`, not recomputed here.
"""
import argparse
import glob
import json
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import torch  # noqa: E402

G_BASE = 131072
ROPE_Q = 16384


def load_checkpoint(model_id):
    from huggingface_hub import snapshot_download
    from safetensors import safe_open
    d = snapshot_download(model_id, allow_patterns=["*.safetensors", "*.json"])
    cfg = json.load(open(os.path.join(d, "config.json")))
    W = {}
    for f in sorted(glob.glob(os.path.join(d, "*.safetensors"))):
        with safe_open(f, "pt") as sf:
            for k in sf.keys():
                W[k] = sf.get_tensor(k)
    return cfg, W


def sylvester(n):
    import numpy as np
    H = np.ones((1, 1), dtype=np.int64)
    while H.shape[0] < n:
        H = np.block([[H, H], [H, -H]])
    return torch.from_numpy(H.astype(np.float64))


def blockdiag(Hn, nb):
    n = Hn.shape[0]
    out = torch.zeros(n * nb, n * nb, dtype=torch.float64)
    for b in range(nb):
        out[b * n:(b + 1) * n, b * n:(b + 1) * n] = Hn
    return out


def q_int8(Wbf16):
    from t16l_stack import quantize_weight_int8
    return quantize_weight_int8(Wbf16)


def scalar(v, dtype):
    return torch.tensor(v, dtype=dtype)


def block_rot_cols(W64, Hb):
    N, K = W64.shape
    return (W64.reshape(N, K // 256, 256) @ Hb).reshape(N, K)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--model", required=True)
    ap.add_argument("--manifest", required=True)
    ap.add_argument("--tp", type=int, default=1)
    ap.add_argument("--out", default="")
    args = ap.parse_args(argv)
    if args.tp != 1:
        print("verify_constants: tensor parallel > 1 is not covered by this tool yet (the rank shards)", flush=True)
        return 2
    from lockstep_manifest import sha256_tensor
    import t16h_lmvariants as LV
    m = json.load(open(args.manifest))
    want = m["constants"]["tensors"]
    if m["family"]["rotation"].get("R1") != "online" or (m.get("smoothing") or {}).get("level"):
        print("verify_constants: this tool covers R1 online at smoothing level 0 (manifest: rotation %s, smoothing %s)"
              % (m["family"]["rotation"], m.get("smoothing")), flush=True)
        return 2
    cfg, W = load_checkpoint(args.model)
    H = int(cfg["hidden_size"]); nq = int(cfg["num_attention_heads"]); nkv = int(cfg.get("num_key_value_heads", nq))
    dh = int(cfg.get("head_dim") or H // nq); L = int(cfg["num_hidden_layers"]); I = int(cfg["intermediate_size"])
    tied = bool(cfg.get("tie_word_embeddings", False)) or ("lm_head.weight" not in W)
    Hn = sylvester(dh) / math.sqrt(dh)
    R2 = bool(m["family"]["rotation"].get("R2", True))         # off by default since Stage 2
    Bv = blockdiag(Hn, nkv).t().contiguous() if R2 else None
    Bo = blockdiag(Hn, nq) if R2 else None
    Hb = sylvester(256) / 16.0
    # v2.5: the outlier channels are a PUBLISHED CHOICE (from calibration statistics, not the
    # checkpoint); the verifier takes them from the manifest and recomputes everything built on them
    outl = {}
    if os.path.isdir(os.path.dirname(args.manifest)):
        from lockstep_manifest import load_constants
        try:
            tens = load_constants(os.path.dirname(args.manifest), m, "cpu")
            for k, t in tens.items():
                if k.endswith(".oidx"):
                    outl[k[:-5]] = t.to(torch.int32).contiguous()
        except Exception as e:
            print("verify_constants: could not read the manifest's outlier channels (%s); v2.4 rules assumed" % e, flush=True)
    print("verify_constants: outliers on %d linears (k=%s)" % (len(outl), (m.get("outliers") or {}).get("k")), flush=True)
    got = {}
    # norms
    for i in range(L):
        for nm in ("input_layernorm", "post_attention_layernorm"):
            g = W["model.layers.%d.%s.weight" % (i, nm)]
            got["model.layers.%d.%s.G" % (i, nm)] = torch.round(g.float() * G_BASE).to(torch.int32).contiguous()
            got["model.layers.%d.%s.s" % (i, nm)] = scalar(float(math.sqrt(g.numel()) / G_BASE), torch.float32)
    gf = W["model.norm.weight"]
    got["model.norm.G"] = torch.round(torch.ones_like(gf).float() * G_BASE).to(torch.int32).contiguous()
    got["model.norm.s"] = scalar(float(math.sqrt(gf.numel()) / G_BASE), torch.float32)
    # layers
    for i in range(L):
        p = "model.layers.%d." % i
        q, k, v = (W[p + "self_attn.%s_proj.weight" % s] for s in ("q", "k", "v"))
        W64 = torch.cat([q, k, v], 0).double()
        qs, ks = q.shape[0], k.shape[0]
        if R2:
            W64[qs + ks:] = Bv @ W64[qs + ks:]
        oq = outl.get(p + "self_attn.qkv_proj")                    # v2.5: the published outlier channels
        if oq is not None:
            got[p + "self_attn.qkv_proj.oidx"] = oq
            got[p + "self_attn.qkv_proj.wo"] = W64[:, oq.long()].to(torch.bfloat16).contiguous()
            W64[:, oq.long()] = 0.0
        W64 = block_rot_cols(W64, Hb)
        W8, ws = q_int8(W64.to(torch.bfloat16))
        got[p + "self_attn.qkv_proj.w8"] = W8; got[p + "self_attn.qkv_proj.ws"] = ws
        got[p + "self_attn.qkv_proj.mode"] = scalar(1, torch.int32)
        if p + "self_attn.q_proj.bias" in W:
            b = torch.cat([W[p + "self_attn.%s_proj.bias" % s] for s in ("q", "k", "v")], 0)
            b64 = b.double()
            if R2:
                b64[qs + ks:] = Bv @ b64[qs + ks:]
            got[p + "self_attn.qkv_proj.bias"] = b64.to(b.dtype).float().contiguous()
        o64 = W[p + "self_attn.o_proj.weight"].double()
        if R2:
            o64 = o64 @ Bo
        oo = outl.get(p + "self_attn.o_proj")                          # v2.5.1
        if oo is not None:
            got[p + "self_attn.o_proj.oidx"] = oo
            got[p + "self_attn.o_proj.wo"] = o64[:, oo.long()].to(torch.bfloat16).contiguous()
            o64[:, oo.long()] = 0.0
        W8, ws = q_int8(o64.to(torch.bfloat16))
        got[p + "self_attn.o_proj.w8"] = W8; got[p + "self_attn.o_proj.ws"] = ws
        got[p + "self_attn.o_proj.mode"] = scalar(0, torch.int32)
        gu = torch.cat([W[p + "mlp.gate_proj.weight"], W[p + "mlp.up_proj.weight"]], 0).double()
        og = outl.get(p + "mlp.gate_up_proj")
        pad = (-I) % 256
        if og is not None:
            wo = gu[:, og.long()].to(torch.bfloat16)
            if pad:
                zo = torch.zeros(pad, wo.shape[1], dtype=wo.dtype)
                wo = torch.cat([wo[:I], zo, wo[I:], zo], 0)
            got[p + "mlp.gate_up_proj.oidx"] = og
            got[p + "mlp.gate_up_proj.wo"] = wo.contiguous()
            gu[:, og.long()] = 0.0
        gu = block_rot_cols(gu, Hb).to(torch.bfloat16)
        if pad:
            z = torch.zeros(pad, gu.shape[1], dtype=gu.dtype)
            gu = torch.cat([gu[:I], z, gu[I:], z], 0)
        W8, ws = q_int8(gu)
        got[p + "mlp.gate_up_proj.w8"] = W8; got[p + "mlp.gate_up_proj.ws"] = ws
        got[p + "mlp.gate_up_proj.mode"] = scalar(1, torch.int32)
        dn = W[p + "mlp.down_proj.weight"].double()
        odn = outl.get(p + "mlp.down_proj")                            # v2.5.1: before the pad and R4
        if odn is not None:
            got[p + "mlp.down_proj.oidx"] = odn
            got[p + "mlp.down_proj.wo"] = dn[:, odn.long()].to(torch.bfloat16).contiguous()
            dn[:, odn.long()] = 0.0
        if pad:
            dn = torch.cat([dn, torch.zeros(dn.shape[0], pad, dtype=dn.dtype)], 1)
        dn = block_rot_cols(dn, Hb)
        W8, ws = q_int8(dn.to(torch.bfloat16))
        got[p + "mlp.down_proj.w8"] = W8; got[p + "mlp.down_proj.ws"] = ws
        got[p + "mlp.down_proj.mode"] = scalar(1, torch.int32)
    # embedding and head
    E = W["model.embed_tokens.weight"]
    got["model.embed_tokens.weight"] = E.contiguous()
    lm = E.clone() if tied else W["lm_head.weight"]
    lm = (lm.double() * gf.double()[None, :]).to(lm.dtype)
    var = LV.build("a15w15").prepare(lm)
    for j, (sh, pl) in enumerate(var.wplanes):
        got["lm_head.plane%d" % j] = pl.t().contiguous().to(torch.int8)
    got["lm_head.ws"] = var.ws.to(torch.float32)
    # rope: vLLM's cache in binary32 on the Q14 grid, sized by the manifest
    rope_names = [n for n in want if n.endswith(".q14")]
    if rope_names:
        shp = want[rope_names[0]]["shape"]
        max_pos, rd = int(shp[0]), int(shp[1])
        base = float(cfg.get("rope_theta", 10000.0))
        inv = 1.0 / (base ** (torch.arange(0, rd, 2, dtype=torch.float) / rd))
        t = torch.arange(max_pos, dtype=torch.float)
        fr = torch.einsum("i,j -> ij", t, inv)
        # vLLM holds the cache in the model dtype (bf16) before the runtime freezes it on the Q14 grid
        cache = torch.cat((fr.cos(), fr.sin()), dim=-1).to(torch.bfloat16).float()
        q14 = (torch.round(cache * ROPE_Q).clamp(-2 * ROPE_Q, 2 * ROPE_Q) / ROPE_Q).contiguous()
        for n in rope_names:
            got[n] = q14
    # compare
    kinds = {}
    detail = []
    for name, rec in want.items():
        kind = name.split(".")[-1]
        if name not in got:
            kinds.setdefault(kind, [0, 0, 0])[2] += 1
            continue
        d = sha256_tensor(got[name])
        ok = d == rec["sha256"]
        kinds.setdefault(kind, [0, 0, 0])[0] += 1
        if ok:
            kinds[kind][1] += 1
        else:
            detail.append({"name": name, "shape": rec.get("shape"), "want": rec["sha256"][:16], "got": d[:16], "got_shape": list(got[name].shape)})
    # the rope table is a PUBLISHED constant, not a recomputable one: cos and sin in binary32
    # differ in the last bit between devices before the Q14 rounding (Qwen2.5-1.5B: 482 of 483
    # tensors recomputed on a CPU match, the q14 table is the one that does not).  It is verified
    # by its hash against the manifest and its derivation is reported here separately.
    rope = kinds.pop("q14", [0, 0, 0])
    total = sum(v[0] for v in kinds.values()); okc = sum(v[1] for v in kinds.values()); skipped = sum(v[2] for v in kinds.values())
    print("VERIFY-CONSTANTS %s: %d tensors in the manifest; constants: %d recomputed, %d match, %d differ, %d not covered; "
          "rope tables (published, device-derived): %d recomputed, %d match the manifest's derivation"
          % (args.model, len(want), total, okc, total - okc, skipped, rope[0], rope[1]), flush=True)
    for kind, (n, k, s) in sorted(kinds.items()):
        print("  %-8s recomputed %4d  match %4d  differ %4d  not covered %d" % (kind, n, k, n - k, s), flush=True)
    for x in detail[:12]:
        print("  DIFF", json.dumps(x), flush=True)
    res = {"model": args.model, "manifest": os.path.abspath(args.manifest), "contract": m["contract_version"], "tensors": len(want),
           "recomputed": total, "match": okc, "differ": total - okc, "not_covered": skipped, "by_kind": kinds,
           "rope_tables": {"recomputed": rope[0], "match": rope[1], "note": "published constant; binary32 cos/sin differ across devices before Q14"},
           "detail": detail[:100]}
    if args.out:
        json.dump(res, open(args.out, "w"), indent=1)
    print("VERIFY-CONSTANTS %s" % ("PASS" if total - okc == 0 and total > 0 else "FAIL"), flush=True)
    return 0 if total - okc == 0 and total > 0 else 3


if __name__ == "__main__":
    sys.exit(main())
